#!/usr/bin/env bash
# Copyright 2023 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

mkdir -p "${GOROOT}/tmp"
case $RUNTIME in
    wazero)
	echo "Running with wazero: $PWD"
	exec wazero run -mount /:/ -env PWD=$PWD -env GOROOT=$GOROOT -env RUNTIME=wazero -hostlogging "$LOG" $1 -- "${@:2}"
    ;;
    wasmedge)
    echo "Running with wasmedge: $PWD"
    exec wasmedge --dir /:/ --env GOROOT=$GOROOT --env PWD=$PWD --env RUNTIME=wasmedge $1 "${@:2}"
    ;;
     *) # wasmtime
	echo "Running with wasmtime: $PWD"
	exec wasmtime --dir / --env GOROOT=$GOROOT --env PWD=$PWD --env RUNTIME=wasmtime --max-wasm-stack 1048576 $1 -- "${@:2}"
    ;;
esac
