#!/usr/bin/env bash
# Copyright 2023 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [[ $RUNTIME == "wazero" ]]; then
	if [[ $LOG == "all" ]]; then
	    LOG="-hostlogging=clock,exit,filesystem,memory,poll,random"
	fi
	echo "Running with wazero: $PWD"
	mkdir -p "${GOROOT}/tmp"
	exec wazero run -mount /:/ -env PWD=$PWD -env GOROOT=$GOROOT -hostlogging "$LOG" $1 -- "${@:2}"
else
	echo "Running with wasmtime: $PWD"
	exec wasmtime --dir=/ --env GOROOT=$GOROOT --env=PWD=$PWD $1 -- "${@:2}"
fi
